---
title: "Dr. Aadil Nakhoda"
description: "Curriculum Vitae"
format: 
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-title: "Sections"
    toc-depth: 2
    number-sections: false
    smooth-scroll: true
    css: styles.css
---

::: {style="text-align: center; margin-bottom: 30px;"}
<p style="font-size: 1.1em; color: #4A4A4A;">

<strong>Nationality:</strong> Pakistani <br> <a href="mailto:anakhoda@iba.edu.pk">anakhoda\@iba.edu.pk</a> \| +92 333 3801363 <br> <a href="https://www.linkedin.com/in/aadil-nakhoda-9569686/" target="_blank">LinkedIn</a> \| <a href="http://sites.google.com/site/aadilnakhoda" target="_blank">Personal Website</a>

</p>

<p style="color: #888888;">

<em>Last Updated: May 2026</em>

</p>
:::

------------------------------------------------------------------------

<hr>

## Executive Summary

I am Assistant Professor at IBA Karachi and an international trade expert, specializing in trade policy, Non-Tariff Measures (NTMs), and export competitiveness. I teach courses on international trade at both undergraduate and graduate-level as well as other core and elective courses in the Economics department at IBA. I also currently serv as the Chair of the Economic Advisory Group, a leading economic advocacy that makes policy recommendations of significant importance to policymakers and provides economic training opportunities to young enthusiasts. I bring extensive consulting and capacity-building experience with the World Bank, USAID, and UN ESCAP on international trading activities, SME trade participation and trade facilitation. I leverage advanced data analytics (using R & STATA) to produce high-impact academic research and actively shapes public policy through regular commentary in leading national dailies.

## Current Position (since July 2014)

**Assistant Professor** at Institute of Business Administration (IBA), Karachi **Research Fellow** at Center for Business and Economic Research (IBA)

## Education

**University of California, Santa Cruz** \| *Santa Cruz, USA* *Ph.D. in International Economics* (June 2012)

**University of California, Santa Cruz** \| *Santa Cruz, USA* *M.A. in International Economics* (December 2009)

**Pennsylvania State University** \| *Pennsylvania, USA* *Bachelor of Science with Honors in Economics* (May 2007)

## Employment History

### Institute of Business Administration, Karachi \| *Pakistan* 

**Assistant Professor** (July 2014 -- Present)

- Teaching undergraduates and graduate students.
- Developing course material, creating course syllabi and outlines, and ensuring effective course delivery.
- Providing evaluation to students and feedback on course performance.

**Research Fellow at CBER** (July 2014 -- Present)

- Conducting regular research work for IBA and different agencies.
- Contributing to the State of the Economy Report as an author and serving as its editor for FY26-27.

------------------------------------------------------------------------

### State Bank of Pakistan \| *Pakistan*

**Zahid Hussain Memorial Research Fellow** (March 2013 -- March 2014)

- Researched issues related to international trade, with a particular focus on trade finance.
- Developed strategies for conducting business surveys, culminating into the business confidence index.

------------------------------------------------------------------------

### University of California, Santa Cruz \| *USA*

**PhD Candidate** (December 2009 -- June 2012)

- Conducted research for my dissertation titled 'Essays on International Trade and Firm Business Strategies'.

**Teaching Assistant** (January 2008 -- April 2012)

- Served as a teaching assistant for various courses offered by the Economics Department at UCSC.

## Publications & Working Papers

- Nakhoda, A. 2025. [Similarity of NTMs and Its Impact on Import Unit Values](https://ideas.repec.org/a/bla/worlde/v48y2025i6p1333-1350.html). *The World Economy*, 48(6), 1333-1350.
- Nakhoda, A. 2025. [Do export subsidies dampen export unit values across markets? A case study on Pakistan](https://ideas.repec.org/a/spr/epolin/v52y2025i2d10.1007_s40812-024-00308-1.html). *Journal of Industrial and Business Economics*, 52(2), 243-273.
- Iqbal, F., Nakhoda, A., Salman, Z., Arshad, E., Aziz, H. & Nabi, I. 2024. [Trade Policy Measures to Encourage a Shift towards Green Technologies](https://www.cdpr.org.pk/wp-content/uploads/2025/01/Trade-Policy-Measures-to-Encourage-a-Shift-Towards-Green-Technologies.pdf), Consortium for Development Policy Research (CDPR). Working Paper.
- Iqbal, F., & Nakhoda, A. 2024. [The Determinants of International Certification among Manufacturing Firms in Pakistan](https://www.researchgate.net/publication/402411461_The_Determinants_of_International_Certification_among_Manufacturing_Firms_in_Pakistan). *The Lahore Journal of Business*, 11(2), 1-28. Presentation at Pakistan Business Council.
- Iqbal, Farrukh & Nakhoda, Aadil. 2024. [Determinants of Management Practices among Manufacturing Firms in Pakistan](https://ideas.repec.org/a/pid/journl/v63y2024i1p45-64.html). *Pakistan Development Review*, pp 45-64.
- Pirzada, A., Nakhoda, A., Mohammad, A. & Javaid, S. 2024. [Pakistan and the rest: A tale of dismal productivity growth, misallocation, and missing transformation](https://ideas.repec.org/p/bri/uobdis/24-778.html), Discussion Paper 24/778, University of Bristol.
- Nakhoda, Aadil. 2023. [Pakistan and EU Trade Potential: The Bottlenecks and Roadmap for Reforms. Friedrich Naumann Foundation for Freedom - Pakistan](https://www.freiheit.org/pakistan/pakistan-and-eu-trade-potential), Islamabad.
- Javed, Maaz, Aadil Nakhoda, & Vaqar Ahmed 2022. ['Micro, small, and medium enterprises amid crisis times: lessons from pandemic experience in Pakistan'](https://sdpi.org/micro-small-and-medium-enterprises-amid-disaster-lessons-from-pakistans-experience/event_detail), Research Report, April, International Development Research Centre and Sustainable Development Policy Institute. Islamabad.
- Nakhoda, Aadil & Niu, Zhaohui. 2022. [Do Chinese technical NTMs increase the exports of less sophisticated products to China?](https://ideas.repec.org/a/mes/chinec/v55y2022i6p425-445.html) *The Chinese Economy*. Vol 55. No. 66, pp 425-445.
- Economic Advisory Group. 2022. [Trade Connectivity](https://eag.org.pk/wp-content/uploads/2025/02/Trade-Connectivity.pdf). Islamabad. PRIME Institute. (Presentation slides at the book launch).
- Nakhoda, Aadil. 2021. [COVID-19 and Disruption in Supply Chains: Case Study of Asia-Pacific Region](https://www.itd.or.th/en/itd-data-center/covid-19-and-disruption-in-supply-chains-case-study-of-asia-pacific-region/). The International Institute for Trade and Development. Bangkok, Thailand.
- Nakhoda, Aadil. 2021. [Regional integration and cooperation of Pakistan in health-related sectors](https://repository.unescap.org/items/26369ca5-8ae6-4276-b4e8-72851b92b508). United Nations ESCAP.
- Ahmed, Vaqar et.al. 2021. Supporting export competitiveness amid COVID-19 in Pakistan. SDPI. Islamabad.
- Iqbal, Farrukh & Nakhoda, Aadil. 2021. [Size and Age as Determinants of Employment Growth among Manufacturing Firms in Pakistan](https://ideas.repec.org/p/pid/wpaper/202027.html), *Pakistan Development Review*, Vol. 60, No.2 pp 119-132.
- Nakhoda, Aadil. 2018. [Do Non-Tariff Measures Matter? Assessing the Impact of Technical Measures to Trade on the Exports of Pakistan In J. Melo & A. Nicita (Eds.) Non-Tariff Measures: Economic Assessment and Policy Options for Development](https://unctad.org/system/files/official-document/ditctab2018d3_en.pdf). Publisher: UNCTAD. [Presentation](https://www.unescap.org/sites/default/files/Session%207%20-%20Do%20NonTariff%20Measures%20Matters.pdf)
- Nakhoda, Aadil. 2018. [The impact of long-term secured loans on exports at the firm-level: The case of a developing country](https://ideas.repec.org/a/taf/jitecd/v27y2018i5p565-584.html). *The Journal of International Trade & Economic Development*. Vol 27. No. 5. pp 565-584.
- Nakhoda, Aadil & Pasha, Farooq. 2017. [The Impact of Manufacturing Activities in the Trading Partner on the Imports into Pakistan](https://www.researchgate.net/publication/339722671_The_impact_of_manufacturing_activities_in_the_trading_partner_on_imports_into_Pakistan). *IBA Business Review*. Vol 12. No. 1.
- Nakhoda, Aadil. 2016. A practical guide to trade policy analysis: A case on Pakistan, Localization for A Practical Guide to Trade Policy Analysis, UNCTAD.
- Nakhoda, Aadil. 2014. [The Influence of Industry Financial Composition on the Exports from Pakistan](https://ideas.repec.org/a/sbp/journl/64.html), *State Bank of Pakistan Research Bulletin*, Vol 10. No 1.
- Nakhoda, Aadil, 2014. [The impact of electricity constraints on access to finance: A firm-level study](https://ideas.repec.org/p/pra/mprapa/59507.html) MPRA Paper 59507, University Library of Munich, Germany.
- Nakhoda, Aadil. 2013. [Bank Competition and Export Diversification](https://ideas.repec.org/p/eei/rpaper/eeri_rp_2013_12.html) EERI Research Paper Series EERI RP 2013/12, Economics and Econometrics Research Institute (EERI), Brussels.
- Nakhoda, Aadil, 2013. [The impact of the exports of BRIC countries plus Turkey on the exports of Pakistan](https://ideas.repec.org/p/pra/mprapa/52477.html) MPRA Paper 52477, University Library of Munich, Germany.
- Nakhoda, Aadil, 2012. [The effect of foreign competition on product switching activities: A firm level analysis](https://ideas.repec.org/p/pra/mprapa/39167.html) MPRA Paper 39167, University Library of Munich, Germany.
- Nakhoda, Aadil, 2012. [The influence of industry financial composition on export flow: A case study of a developing financial market](https://ideas.repec.org/p/pra/mprapa/43792.html) MPRA Paper 43792, University Library of Munich, Germany.
- Nakhoda, Aadil, 2012. [The influence of financial leverage of firms on their international trading activities](https://ideas.repec.org/p/pra/mprapa/35765.html) MPRA Paper 35765, University Library of Munich, Germany.

## Teaching

Taught courses on International Trade (Undergraduate, Masters and PhD-level), Macroeconomics (Undergraduate and MBA-level), International Political Economy (MBA-level) Development Economics (Undergraduate - level), History of Economic Thought (Undergraduate-level), Intermediate Microeconomics (Undergraduate-level) at Institute of Business Administration, Karachi.

## Professional Activities

- Member of Economic Advisory Group under the auspices of PRIME Institute January 2021-Present. (Chair from January 2025).
- Coordinator for Asia Pacific Research and Training Network on Trade at IBA, Karachi August 2017 - Present. Have attended workshops (both online and in-person), organized guest lectures at IBA and participated in panels hosted by United Nations ESCAP and ARTNeT.
- Coordinator for United Nations Conference on Trade and Development (UNCTAD) Virtual Institute at IBA, Karachi. January 2016- Present. Have attended online workshops and organized guest lectures hosting speakers from UNCTAD at IBA.

## Major Activities

- Trade expert in project on identifying and formulating specific reforms impacting foreign investments in Pakistan with Adam Smith International and PRIME.
- Member of organizing team of the IBA-CBER conferences and moderated panel sessions at the conferences.
- Regularly discuss international trade-related issues on different online platforms. Recent events: Infer, PRIME, CBER.
- Conducted workshops on trade-related resources and information gathering for various participants belonging to academia, industry, and government. Delivered an orientation on FTAs and GSP Plus to women-led entrepreneurs across major cities in Pakistan in April 2023.
- Attended various workshops and seminars hosted by United Nations ESCAP and UNCTAD Virtual Institute on international trade related topics such as trade intelligence and negotiation, trade facilitation, resolution of trade disputes and sustainable development.
- Regularly publish newspaper articles on issues faced by industries and businesses as well as on issues related to international trade in Express Tribune. Have also published numerous articles in Dawn, Profit, Business Recorder Research and South Asia magazine.
- Participated as speaker in webinars for United Nations ESCAP, World Bank, SDPI, Pakistan Institute of Development Economics (PIDE), Learners' Republic, Centre for Excellence in Journalism (CEJ-IBA) on trade related issues, including topics on trade dispute.
- Panelist on a webinar hosted by PIDE, World Bank and International Trade Center on Experiences of Pakistani Exporters with Non-Tariff Measures in October 2020.
- Panelist on various webinars and seminars with a focus on trade-related issues including trade facilitation, trade reforms and resolution of trade-related disputes.

## Completed Projects

- **Consortium for Development Policy Research (CDPR):** International Trade expert for project on green trade. Determined how much imports are to increase if Pakistan relaxes import tariffs on various green goods. 2024.
- **USAID:** Supporting New Opportunities Post-Covid-19 for Export and Domestic Market Development for SMEs in Current Policy and Regulatory Environment. 2021.
- **SDPI & UN ESCAP:** Project with Sustainable Development Policy Institute (SDPI) on Supporting Export Competitiveness amid COVID-19 in Pakistan and with United Nations ESCAP on Health and Trade Integration completed in March 2021. These involved discussion on improving trade facilitation.
- **State Bank of Pakistan (SBP):** Developing and compiling bi-monthly Business Confidence Index. 2016-Present.
- **Trade Development Authority of Pakistan (TDAP):** Designing and delivering National Exporters Training Program across major cities of Pakistan. 2018-2020.
- **Adam Smith International (ASI) and DFID:** Pakistan Trade Scoping Study. 2018-2019.
- **UNCTAD:** Research article on the impact of NTMs faced by Pakistani exporters published as a chapter in J. Melo & A. Nicita (Eds.) Non-Tariff Measures: Economic Assessment and Policy Options for Development. 2018.
- **World Bank:** Regional Competitiveness Initiative for Textile Sector in Pakistan. 2014-2015.

## Training Workshops and Courses

*Selected Courses involving Trade Dispute and Trade Facilitation*

- Services Trade and Services Provisions in RTAs (Aug 2024)
- E-learning course on optimizing trade agreement analysis (Mar 2024)
- Facilitated Online Course on Trade and SDGs (Nov 2023)
- Climate-smart Trade and Investment for Sustainable Development (Sep 2023)
- Facilitated Online Course on Next Generation Trade Facilitation (Dec 2022)
- Sustainable Development Provisions in FTAs (May 2022)
- Pilot Course on Negotiating Regional Trade Agreements for Trade in Times of Crisis and Pandemic (Aug 2021)
- Negotiation of Comprehensive Economic Partnership Agreements (Jun 2021)
- Enhancing Online National Trade Portals and Repositories (Sep 2020)
- Business Process Analysis (Aug 2020)

## Skills

- Excellent data management and analytic skills using STATA and R. Regularly use Latex, R and Microsoft Office for preparing reports, presentations, research papers and other documents.
- Well versed in the use and application of more commonly used trade-related databases such as UN Comtrade, World Bank's WITS, Trademap.org and CEPII's BACI dataset.
- Excellent academic research level competency, particularly in the application of trade related databases as shown by the publications listed. Have used resources such as UNCTAD'S NTMs Hub, United Nations ESCAP'S TINA and RIVA and other databases in various research studies.

## Service to IBA

- Member of Board of Studies of the Economics Department and Member of Student Conduct and IBA Standards Committee (SCISC).
- Regularly participate in internal assessment of different majors and programs offered at the Economics Department at IBA.
- Regular contribution to State of the Economy Report by CBER and Economics faculty at IBA. Editor for FY27 Report.

## Selected Video & Media Appearances

- **Guest Panelist:** [One Big Idea 2: What Pakistan's Top Economists Would Fix](https://www.youtube.com/watch?v=EBUr6VYosEk) \| Haque Economics
- **Guest Speaker:** [Can Pakistan Build a Competitive Economy? Role of Research, Collaboration & Trade Policies](https://www.youtube.com/watch?v=P6zdMHaKO34) \| SIA Conversation
- **Guest Speaker:** [How to Design the National Tariff Policy](https://www.youtube.com/watch?v=tfV_fT_ctiU) \| PRIME Institute
- **Guest Panelist:** [Should India-Pakistan Trade Resume?](https://www.youtube.com/watch?v=-WvRaWCFlEM) \| InferTalks
- **Guest Speaker:** [A talk on 'Pakistan Trade Landscape'](https://www.youtube.com/watch?v=h_m9w7oGRCA) \| Pakistan Single Window (PSW)
- **Guest Panelist:** [Export Facilitation Scheme (EFS) - Trade Made Easy Webinar Series](https://www.youtube.com/watch?v=fCoP4QKSYf0) \| SDPI & PSW
- **Interviewee:** [Agenda Setting for Climate Change: How can academic research generate policy impact within the energy sector?](https://www.youtube.com/watch?v=QZPRcOPUR1Q) \| CDPR & The World Bank
- **Guest Speaker:** Building the Economy of Pakistan with Innovative & Competitive Goods
- **Guest Panelist:** [Trump's Tariffs - Will tariffs reduce the US trade deficit?](https://www.youtube.com/watch?v=zScZc9e4VyM) \| Naya Pakistan, Geo News
- **Guest Speaker:** [Economic Commentary and Analysis](INSERT_AGN_NEWS_URL_HERE) \| AGN News
- **Guest Panelist:** [IRAN–US/ISRAEL WAR FALLOUT ON PAKISTAN’S ECONOMY](https://www.youtube.com/watch?v=hP4-nNp9T4o) \| Pakistan Economics Frontier
- **Guest Panelist:** [Trump's Trade Shock as A Wake-Up Call for Pakistan](https://www.youtube.com/watch?v=2RGRPAzvG3A) \| Pakistan Economics Frontier
- **Guest Panelist:** [A Conversation on Pakistan's Trade Competitiveness with Aadil Nakhoda by Learners' Republic](https://www.youtube.com/watch?v=PR03PWhuVkg) \| Learners' Republic
- **Guest Speaker:** [Building the Economy of Pakistan with Innovative & Competitive Goods w/ Aadil Nakhoda](https://www.youtube.com/watch?v=aVtu18u9u2I&list=PLuDynTEquvOKf41t7P33mEaCrEufJMnyA) \| PRIME Institute
